spring.application.name=SpringRestApi

server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*

management.server.port=13000

management.info.env.enabled=true
info.app.name=OrderService
info.app.version=1.0.0
info.app.owner=Team-A

