package org.example.pojo;

import jakarta.persistence.*;

@Entity
/* when your table name is diff in database and ClassName use this annotation over pojo class*/
@Table(name = "employees")
public class Employee {

    @Id
    /*generated value fetch the value generated by sql,used when we use auto increment in table id*/
    @GeneratedValue(strategy = GenerationType.IDENTITY)// to verify run in debug mode and check
    private int empId;
    private String name;
    private String position;
    /*when column name and java class field name is diff we get error, so we need to use @Column over field*/
    @Column(name = "sal")
    private double salary;

    public Employee(){ }

    public Employee(int id, String name, String position, double salary) {

        this.empId = id;
        this.name = name;
        this.position = position;
        this.salary = salary;
    }

    public Employee(String name, String position, double salary) {
        this.name = name;
        this.position = position;
        this.salary = salary;
    }

    public int getEmpId() {
        return empId;
    }

    public void setEmpId(int empId) {
        this.empId = empId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        return "Employees{" +
                "id=" + empId +
                ", name='" + name + '\'' +
                ", position='" + position + '\'' +
                ", salary=" + salary +
                '}';
    }
}
